<a href="https://colab.research.google.com/github/pallavrouth/AI-Bootcamp/blob/main/intropy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python as calculator

In [ ]:
# Addition and subtraction
print(5 + 5)
print(5 - 5)

# Multiplication and division
print(3 * 5)
print(10 / 2)

# Exponentiation
print(4 ** 2)

# Modulo
print(18 % 7)

# How much is your $100 worth after 7 years?
print(100*1.1**7)

# Variable assignment and computations

Income and savings

In [ ]:
# Create a variable savings
savings = 100

# Create a variable income
income = 500

# Print out savings
print(savings)

# Print out expense
expense = income - savings
print(expense)

100
400


Making money

In [ ]:
# Create a variable savings
savings = 100

# Create interest rate per year
interest_rate = 10/100
print(interest_rate)

# Calculate growth in savings after a year
growth_in_savings = savings + savings * interest_rate

# Print out result
print(growth_in_savings)

# Calculate growth in savings after 2 years
# growth_in_savings = savings + savings * interest_rate + savings * interest_rate
# growth_in_savings = savings + 2 * ( savings * interest_rate ) 
n_years = 2
growth_in_savings = savings + n_years * ( savings * interest_rate ) 
print(growth_in_savings)

In [ ]:
# Create a variable desc
interest_type = 'simple interest'

# Create a variable profitable
profitable = True

Using the + operator to paste together two strings can be very useful in building custom messages.

To fix the error, you'll need to explicitly convert the types of your variables. More specifically, you'll need str(), to convert a value into a string. str(savings), for example, will convert the integer savings to a string.

Similar functions such as int(), float() and bool() will help you convert Python values into any type.

In [ ]:
# Fix the printout
print("I started with $" + str(savings) + " and now have $" + str(growth_in_savings) + ". Awesome!")

# Definition of pi_string
pi_string = "3.1415926"

# Convert pi_string into float: pi_float
pi_float = float(pi_string)
print(pi_float)

In [ ]:
# Find types of variables
print(type(interest_type))
print(type(profitable))
print(type(growth_in_savings))

<class 'str'>
<class 'bool'>
<class 'float'>


# List

Things in my room and prices

In [ ]:
# area variables (in square meters)
laptop = 1200.00
monitor = 100.00
notebook = 3.00
chair = 30.00
table = 100.00

# Create list prices
prices = [laptop,monitor,notebook,chair,table]

# Print areas
print(prices)

[1200.0, 100.0, 3.0, 30.0, 100.0]


A list can contain any Python type. Although it's not really common, a list can also contain a mix of Python types including strings, floats, booleans, etc.

Add meaningful names

In [ ]:
prices = ["laptop",laptop,"monitor",monitor,"notebook",notebook,"chair",chair,"table",table]
print(prices)

['laptop', 1200.0, 'monitor', 100.0, 'notebook', 3.0, 'chair', 30.0, 'table', 100.0]


More meaningful with list of list

In [ ]:
prices = [["laptop",laptop],["monitor",monitor],["notebook",notebook],["chair",chair],["table",table]]
print(prices)

[['laptop', 1200.0], ['monitor', 100.0], ['notebook', 3.0], ['chair', 30.0], ['table', 100.0]]


In [ ]:
type(prices)

list

**Subsetting lists**

In [ ]:
prices[0]
prices[1]
prices[-1]

['laptop', 1200.0]

**Subset and calculate**

In [ ]:
# The prices list again
prices = ["laptop",laptop,"monitor",monitor,"notebook",notebook,"chair",chair,"table",table]

# Sum of price of electronics
sum_price_electronics = prices[1] + prices[3]

# Print the variable eat_sleep_area
print(sum_price_electronics)

A Python list can contain practically anything; even other lists! To subset lists of lists, you can use the same technique as before: square brackets. 

**Slicing and dicing**

Selecting single values from a list is just one part of the story. It's also possible to slice your list, which means selecting multiple elements from your list. Use the following syntax: `list[start:end]`

*The start index will be included, while the end index is not.*

However, it's also possible not to specify these indexes. If you don't specify the begin index, Python figures out that you want to start your slice at the beginning of your list. If you don't specify the end index, the slice will go all the way to the last element of your list. 

In [ ]:
laptop = 1200
monitor = 100
notebook = 3
chair = 30
table = 100

prices = [1200,100,3,30,100]

# Use slicing to create electronics
electronics = prices[:2]

# Use slicing to create furniture
furniture = prices[3:]

# Print out downstairs and upstairs
print(electronics)
print(furniture)

Modify list

In [ ]:
# add element to list
prices = ["laptop",laptop,"monitor",monitor,"notebook",notebook,"chair",chair,"table",table]
prices[-2] = "height adjustable table"
print(prices)

In [ ]:
# add lists by pasting them
prices = ["laptop",laptop,"monitor",monitor,"notebook",notebook,"chair",chair,"table",table] + ["cup",10]
print(prices)

Finally, you can also remove elements from your list. You can do this with the `del` statement

```
x = ["a", "b", "c", "d"]
del(x[1])
```

The Python code in the script already creates a list with the name areas and a copy named areas_copy. Next, the first element in the areas_copy list is changed and the areas list is printed out. If you hit Run Code you'll see that, although you've changed areas_copy, the change also takes effect in the areas list. That's because areas and areas_copy point to the same list.

If you want to prevent changes in areas_copy from also taking effect in areas, you'll have to do a more explicit copy of the areas list. You can do this with `list()` or by using `[:]`.

In [ ]:
prices = [1200,100,3,30,100]
# not an explicit copy
prices_copy = prices
prices_copy[0] = 1205
print(prices)

[1205, 100, 3, 30, 100]


In [ ]:
prices = [1200,100,3,30,100]
# explicit compy
prices_copy = prices[:]
prices_copy[0] = 1205
print(prices)

# Functions and packages

Simple functions we already use. Uses the syntax function_name(args)

In [ ]:
print(len(prices))
print(type(savings))

In [ ]:
?len

Multiple arguments

In [ ]:
print(prices)
#print(sorted(prices))
#print(sorted(prices,reverse = True))

['laptop', 1200.0, 'monitor', 100.0, 'notebook', 3.0, 'chair', 30.0, 'table', 100.0, 'cup', 10]


**Methods** are special functions that only operate only objects that has a specific class. For example the append method for list and the upper method for strings. They follow the syntax `object.method(args)`

Functions are executed as `function_name(args)` and not necessarily created with objects in minds. They are generally `package_name.function_name(args)`

In [ ]:
# string to experiment with: room
place = "poolhouse"

# Use upper() on room: room_up
place_up = place.upper()

# Print out room and room_up
print(place)
print(place_up)

# Print out the number of o's in room
print(place.count("o"))

poolhouse
POOLHOUSE
3


In [ ]:
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Print out the index of the element 20.0
print(areas.index(20.0))

# Print out how often 14.5 appears in areas
print(areas.count(9.50))

2
1


In [ ]:
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Use append twice to add poolhouse and garage size
areas.append(24.5)
areas.append(15.45)

# Print out areas
print(areas)

# Reverse the orders of the elements in areas
areas.reverse()

# Print out areas
print(areas)

[11.25, 18.0, 20.0, 10.75, 9.5, 24.5, 15.45]
[15.45, 24.5, 9.5, 10.75, 20.0, 18.0, 11.25]


In [ ]:
# Definition of radius
r = 0.43

# Import the math package
import math

# Calculate C
C = 2*math.pi*r

# Calculate A
A = math.pi*r**2

# Build printout
print("Circumference: " + str(C))
print("Area: " + str(A))

Circumference: 2.701769682087222
Area: 0.5808804816487527


In [ ]:
# Definition of radius
r = 192500

# Import radians function of math package
from math import radians

# Travel distance of Moon over 12 degrees. Store in dist.
phi = radians(12)
dist = r*phi

# Print out dist
print(dist)

# Numpy

In [ ]:
import numpy as np

Heart disease since 2015 



In [ ]:
heart_disease = [0.633,0.635,0.647,0.657,0.659,0.690]

In [ ]:
print(np.array(heart_disease))
print(type(np.array(heart_disease)))

[2.71 2.74 2.81 2.83 2.85 3.35]
<class 'numpy.ndarray'>


In [ ]:
np_heart_disease = np.array(heart_disease)
# simple operations
np_heart_disease * 10e6

array([6330000., 6350000., 6470000., 6570000., 6590000., 6900000.])

In [ ]:
# cancer deaths since 2015
np_cancer = np.array([0.595,0.598,0.599,0.599,0.599,0.598])

**Element by element operation**

In [ ]:
ratio = np_heart_disease / np_cancer
print(ratio)

[1.06386555 1.06187291 1.08013356 1.09682805 1.10016694 1.15384615]


More intuitive to subset compared to lists. To subset both regular Python lists and numpy arrays, you can use square brackets. For numpy specifically, you can also use boolean numpy arrays:

In [ ]:
# heart disease cases less than 0.65
print(np_heart_disease < 0.65)
# assign this to object low
low = np_heart_disease < 0.65
# now subset
print(np_heart_disease[low])

[ True  True  True False False False]
[0.633 0.635 0.647]


Numpy arrays cannot **contain elements with different types**. If you try to build such a list, some of the elements' types are changed to end up with a homogeneous list. This is known as type coercion.

**2 D numpy arrays**

In [ ]:
# heart disease deaths and year information
heart_disease = [[2015,0.633],
                 [2016,0.635],
                 [2017,0.647],
                 [2018,0.657],
                 [2019,0.659],
                 [2020,0.690]]

# create a 2D numpy array
heart_disease_2d = np.array(heart_disease)

print(heart_disease_2d)

In [ ]:
heart_disease_2d.shape
heart_disease_2d[3,:]
heart_disease_2d[:,1]

array([0.633, 0.635, 0.647, 0.657, 0.659, 0.69 ])

Easy to perform simple arithmetic operations

In [ ]:
# mean
np.mean(heart_disease_2d[:,1])

0.6535